on:
  release:
    types: [published]

name: publish-docker

jobs:
  docker:
    uses: "shivjm/dockerfile-image-tags/.github/workflows/docker.yml@1070526d9f21130977ce12eda4905e0bab821a54"
    with:
      push: true
      # can’t use an env variable: https://github.com/actions/runner/issues/480
      tags: |
        ghcr.io/shivjm/dockerfile-image-tags:latest
        ghcr.io/shivjm/dockerfile-image-tags:${{ github.event.release.tag_name }}
