on:
  release:
    types: [published]

name: publish-docker

env:
  image: ghcr.io/shivjm/dockerfile-image-tags

jobs:
  docker:
    uses: "shivjm/dockerfile-image-tags/.github/workflows/docker.yml@1070526d9f21130977ce12eda4905e0bab821a54"
    with:
      push: true
      tags: |
        ${{ env.image}}:latest
        ${{ env.image }}:${{ github.event.release.tag_name }}
